rebuilt again
due to
cups-filters-1.0.68/filter/pdftopdf/qpdf_pdftopdf_processor.cc:23: undefined reference to `QUtil::double_to_string[abi:cxx11](double, int)'